const LOCAL_DATABASE = {
  "sets": [
    { "id": "me55", "name": "30th Celebration", "total": 199, "releaseDate": "2026/09/16", "images": { "logo": "https://images.pokemontcg.io/me55/logo.png" } },
    { "id": "me5", "name": "Mega Evolution — Pitch Black", "total": 115, "releaseDate": "2026/07/17", "images": { "logo": "https://images.pokemontcg.io/me5/logo.png" } },
    { "id": "me4", "name": "Mega Evolution — Chaos Rising", "total": 180, "releaseDate": "2026/05/22", "images": { "logo": "https://images.pokemontcg.io/me4/logo.png" } },
    { "id": "me3", "name": "Mega Evolution — Perfect Order", "total": 190, "releaseDate": "2026/03/27", "images": { "logo": "https://images.pokemontcg.io/me3/logo.png" } },
    { "id": "me2", "name": "Mega Evolution — Ascended Heroes", "total": 295, "releaseDate": "2026/01/30", "images": { "logo": "https://images.pokemontcg.io/me2/logo.png" } },
    { "id": "me1", "name": "Mega Evolution — Phantasmal Flames", "total": 210, "releaseDate": "2025/11/14", "images": { "logo": "https://images.pokemontcg.io/me1/logo.png" } },
    { "id": "me0", "name": "Mega Evolution Base Set", "total": 185, "releaseDate": "2025/09/26", "images": { "logo": "https://images.pokemontcg.io/me0/logo.png" } },
    { "id": "sv9", "name": "Scarlet & Violet — Black Bolt / White Flare", "total": 175, "releaseDate": "2025/07/18", "images": { "logo": "https://images.pokemontcg.io/sv9/logo.png" } },
    { "id": "sv85a", "name": "Scarlet & Violet — Destined Rivals", "total": 182, "releaseDate": "2025/05/30", "images": { "logo": "https://images.pokemontcg.io/sv85a/logo.png" } },
    { "id": "sv85", "name": "Scarlet & Violet — Journey Together", "total": 195, "releaseDate": "2025/03/28", "images": { "logo": "https://images.pokemontcg.io/sv85/logo.png" } },
    { "id": "sv81", "name": "Scarlet & Violet — Prismatic Evolutions", "total": 175, "releaseDate": "2025/01/17", "images": { "logo": "https://images.pokemontcg.io/sv81/logo.png" } },
    { "id": "sv8", "name": "Surging Sparks", "total": 250, "releaseDate": "2024/11/08", "images": { "logo": "https://images.pokemontcg.io/sv8/logo.png" } },
    { "id": "sv7f", "name": "Stellar Crown", "total": 170, "releaseDate": "2024/09/13", "images": { "logo": "https://images.pokemontcg.io/sv7f/logo.png" } },
    { "id": "sv65", "name": "Shrouded Fable", "total": 99, "releaseDate": "2024/08/02", "images": { "logo": "https://images.pokemontcg.io/sv65/logo.png" } },
    { "id": "sv6", "name": "Twilight Masquerade", "total": 226, "releaseDate": "2024/05/24", "images": { "logo": "https://images.pokemontcg.io/sv6/logo.png" } },
    { "id": "sv5", "name": "Temporal Forces", "total": 218, "releaseDate": "2024/03/22", "images": { "logo": "https://images.pokemontcg.io/sv5/logo.png" } },
    { "id": "sv45", "name": "Paldean Fates", "total": 245, "releaseDate": "2024/01/26", "images": { "logo": "https://images.pokemontcg.io/sv45/logo.png" } },
    { "id": "sv4", "name": "Paradox Rift", "total": 266, "releaseDate": "2023/11/03", "images": { "logo": "https://images.pokemontcg.io/sv4/logo.png" } },
    { "id": "sv35", "name": "151", "total": 207, "releaseDate": "2023/09/22", "images": { "logo": "https://images.pokemontcg.io/sv35/logo.png" } },
    { "id": "sv3", "name": "Obsidian Flames", "total": 230, "releaseDate": "2023/08/11", "images": { "logo": "https://images.pokemontcg.io/sv3/logo.png" } },
    { "id": "sv2", "name": "Paldea Evolved", "total": 279, "releaseDate": "2023/06/09", "images": { "logo": "https://images.pokemontcg.io/sv2/logo.png" } },
    { "id": "sv1", "name": "Scarlet & Violet", "total": 258, "releaseDate": "2023/03/31", "images": { "logo": "https://images.pokemontcg.io/sv1/logo.png" } },
    { "id": "swsh12pt5", "name": "Crown Zenith", "total": 160, "releaseDate": "2023/01/20", "images": { "logo": "https://images.pokemontcg.io/swsh12pt5/logo.png" } },
    { "id": "swsh12", "name": "Silver Tempest", "total": 215, "releaseDate": "2022/11/11", "images": { "logo": "https://images.pokemontcg.io/swsh12/logo.png" } },
    { "id": "swsh11", "name": "Lost Origin", "total": 217, "releaseDate": "2022/09/09", "images": { "logo": "https://images.pokemontcg.io/swsh11/logo.png" } },
    { "id": "swsh10", "name": "Astral Radiance", "total": 216, "releaseDate": "2022/05/27", "images": { "logo": "https://images.pokemontcg.io/swsh10/logo.png" } },
    { "id": "swsh9", "name": "Brilliant Stars", "total": 186, "releaseDate": "2022/02/25", "images": { "logo": "https://images.pokemontcg.io/swsh9/logo.png" } },
    { "id": "swsh8", "name": "Fusion Strike", "total": 284, "releaseDate": "2021/11/12", "images": { "logo": "https://images.pokemontcg.io/swsh8/logo.png" } },
    { "id": "swsh7", "name": "Evolving Skies", "total": 237, "releaseDate": "2021/08/27", "images": { "logo": "https://images.pokemontcg.io/swsh7/logo.png" } },
    { "id": "swsh6", "name": "Chilling Reign", "total": 233, "releaseDate": "2021/06/18", "images": { "logo": "https://images.pokemontcg.io/swsh6/logo.png" } },
    { "id": "swsh5", "name": "Battle Styles", "total": 183, "releaseDate": "2021/03/19", "images": { "logo": "https://images.pokemontcg.io/swsh5/logo.png" } },
    { "id": "swsh45", "name": "Shining Fates", "total": 73, "releaseDate": "2021/02/19", "images": { "logo": "https://images.pokemontcg.io/swsh45/logo.png" } },
    { "id": "swsh4", "name": "Vivid Voltage", "total": 203, "releaseDate": "2020/11/13", "images": { "logo": "https://images.pokemontcg.io/swsh4/logo.png" } },
    { "id": "swsh3", "name": "Darkness Ablaze", "total": 201, "releaseDate": "2020/08/14", "images": { "logo": "https://images.pokemontcg.io/swsh3/logo.png" } },
    { "id": "swsh2", "name": "Rebel Clash", "total": 209, "releaseDate": "2020/05/01", "images": { "logo": "https://images.pokemontcg.io/swsh2/logo.png" } },
    { "id": "swsh1", "name": "Sword & Shield", "total": 216, "releaseDate": "2020/02/07", "images": { "logo": "https://images.pokemontcg.io/swsh1/logo.png" } },
    { "id": "sm12", "name": "Cosmic Eclipse", "total": 271, "releaseDate": "2019/11/01", "images": { "logo": "https://images.pokemontcg.io/sm12/logo.png" } },
    { "id": "sm115", "name": "Hidden Fates", "total": 69, "releaseDate": "2019/08/23", "images": { "logo": "https://images.pokemontcg.io/sm115/logo.png" } },
    { "id": "sm11", "name": "Unified Minds", "total": 258, "releaseDate": "2019/08/02", "images": { "logo": "https://images.pokemontcg.io/sm11/logo.png" } },
    { "id": "sm10", "name": "Unbroken Bonds", "total": 234, "releaseDate": "2019/05/03", "images": { "logo": "https://images.pokemontcg.io/sm10/logo.png" } },
    { "id": "sm9", "name": "Team Up", "total": 196, "releaseDate": "2019/02/01", "images": { "logo": "https://images.pokemontcg.io/sm9/logo.png" } },
    { "id": "sm8", "name": "Lost Thunder", "total": 236, "releaseDate": "2018/11/02", "images": { "logo": "https://images.pokemontcg.io/sm8/logo.png" } },
    { "id": "sm7", "name": "Celestial Storm", "total": 183, "releaseDate": "2018/08/03", "images": { "logo": "https://images.pokemontcg.io/sm7/logo.png" } },
    { "id": "sm6", "name": "Forbidden Light", "total": 146, "releaseDate": "2018/05/04", "images": { "logo": "https://images.pokemontcg.io/sm6/logo.png" } },
    { "id": "sm5", "name": "Ultra Prism", "total": 178, "releaseDate": "2018/02/02", "images": { "logo": "https://images.pokemontcg.io/sm5/logo.png" } },
    { "id": "sm4", "name": "Crimson Invasion", "total": 124, "releaseDate": "2017/11/03", "images": { "logo": "https://images.pokemontcg.io/sm4/logo.png" } },
    { "id": "sm3", "name": "Burning Shadows", "total": 169, "releaseDate": "2017/08/04", "images": { "logo": "https://images.pokemontcg.io/sm3/logo.png" } },
    { "id": "sm2", "name": "Guardians Rising", "total": 169, "releaseDate": "2017/05/05", "images": { "logo": "https://images.pokemontcg.io/sm2/logo.png" } },
    { "id": "sm1", "name": "Sun & Moon", "total": 163, "releaseDate": "2017/02/03", "images": { "logo": "https://images.pokemontcg.io/sm1/logo.png" } },
    { "id": "xy12", "name": "Evolutions", "total": 109, "releaseDate": "2016/11/02", "images": { "logo": "https://images.pokemontcg.io/xy12/logo.png" } },
    { "id": "xy11", "name": "Steam Siege", "total": 116, "releaseDate": "2016/08/03", "images": { "logo": "https://images.pokemontcg.io/xy11/logo.png" } },
    { "id": "xy10", "name": "Fates Collide", "total": 125, "releaseDate": "2016/05/02", "images": { "logo": "https://images.pokemontcg.io/xy10/logo.png" } },
    { "id": "xy9", "name": "BREAKpoint", "total": 123, "releaseDate": "2016/02/03", "images": { "logo": "https://images.pokemontcg.io/xy9/logo.png" } },
    { "id": "xy8", "name": "BREAKthrough", "total": 164, "releaseDate": "2015/11/04", "images": { "logo": "https://images.pokemontcg.io/xy8/logo.png" } },
    { "id": "xy7", "name": "Ancient Origins", "total": 100, "releaseDate": "2015/08/12", "images": { "logo": "https://images.pokemontcg.io/xy7/logo.png" } },
    { "id": "xy6", "name": "Roaring Skies", "total": 110, "releaseDate": "2015/05/06", "images": { "logo": "https://images.pokemontcg.io/xy6/logo.png" } },
    { "id": "xy5", "name": "Primal Clash", "total": 164, "releaseDate": "2015/02/04", "images": { "logo": "https://images.pokemontcg.io/xy5/logo.png" } },
    { "id": "xy4", "name": "Phantom Forces", "total": 122, "releaseDate": "2014/11/05", "images": { "logo": "https://images.pokemontcg.io/xy4/logo.png" } },
    { "id": "xy3", "name": "Furious Fists", "total": 113, "releaseDate": "2014/08/13", "images": { "logo": "https://images.pokemontcg.io/xy3/logo.png" } },
    { "id": "xy2", "name": "Flashfire", "total": 109, "releaseDate": "2014/05/07", "images": { "logo": "https://images.pokemontcg.io/xy2/logo.png" } },
    { "id": "xy1", "name": "XY", "total": 146, "releaseDate": "2014/02/05", "images": { "logo": "https://images.pokemontcg.io/xy1/logo.png" } },
    { "id": "base3", "name": "Fossil", "total": 62, "releaseDate": "1999/10/10", "images": { "logo": "https://images.pokemontcg.io/base3/logo.png" } },
    { "id": "base2", "name": "Jungle", "total": 64, "releaseDate": "1999/06/16", "images": { "logo": "https://images.pokemontcg.io/base2/logo.png" } },
    { "id": "base1", "name": "Base Set", "total": 102, "releaseDate": "1999/01/09", "images": { "logo": "https://images.pokemontcg.io/base1/logo.png" } }
  ]
};