const LOCAL_DATABASE = {
  "sets": [
    { "id": "sv08", "name": "Surging Sparks", "total": 250, "images": { "logo": "https://images.pokemontcg.io/sv08/logo.png" } },
    { "id": "sv07", "name": "Stellar Crown", "total": 170, "images": { "logo": "https://images.pokemontcg.io/sv07/logo.png" } },
    { "id": "sv06.5", "name": "Shrouded Fable", "total": 99, "images": { "logo": "https://images.pokemontcg.io/sv06.5/logo.png" } },
    { "id": "sv06", "name": "Twilight Masquerade", "total": 226, "images": { "logo": "https://images.pokemontcg.io/sv06/logo.png" } },
    { "id": "sv05", "name": "Temporal Forces", "total": 218, "images": { "logo": "https://images.pokemontcg.io/sv05/logo.png" } },
    { "id": "sv04.5", "name": "Paldean Fates", "total": 245, "images": { "logo": "https://images.pokemontcg.io/sv04.5/logo.png" } },
    { "id": "sv04", "name": "Paradox Rift", "total": 266, "images": { "logo": "https://images.pokemontcg.io/sv04/logo.png" } },
    { "id": "sv03.5", "name": "151", "total": 207, "images": { "logo": "https://images.pokemontcg.io/sv03.5/logo.png" } },
    { "id": "sv03", "name": "Obsidian Flames", "total": 230, "images": { "logo": "https://images.pokemontcg.io/sv03/logo.png" } },
    { "id": "sv02", "name": "Paldea Evolved", "total": 279, "images": { "logo": "https://images.pokemontcg.io/sv02/logo.png" } },
    { "id": "sv01", "name": "Scarlet & Violet", "total": 258, "images": { "logo": "https://images.pokemontcg.io/sv01/logo.png" } },
    { "id": "swsh12pt5", "name": "Crown Zenith", "total": 160, "images": { "logo": "https://images.pokemontcg.io/swsh12pt5/logo.png" } },
    { "id": "swsh12", "name": "Silver Tempest", "total": 215, "images": { "logo": "https://images.pokemontcg.io/swsh12/logo.png" } },
    { "id": "swsh11", "name": "Lost Origin", "total": 217, "images": { "logo": "https://images.pokemontcg.io/swsh11/logo.png" } },
    { "id": "swsh10", "name": "Astral Radiance", "total": 216, "images": { "logo": "https://images.pokemontcg.io/swsh10/logo.png" } },
    { "id": "swsh9", "name": "Brilliant Stars", "total": 186, "images": { "logo": "https://images.pokemontcg.io/swsh9/logo.png" } },
    { "id": "swsh8", "name": "Fusion Strike", "total": 284, "images": { "logo": "https://images.pokemontcg.io/swsh8/logo.png" } },
    { "id": "swsh7", "name": "Evolving Skies", "total": 237, "images": { "logo": "https://images.pokemontcg.io/swsh7/logo.png" } },
    { "id": "swsh6", "name": "Chilling Reign", "total": 233, "images": { "logo": "https://images.pokemontcg.io/swsh6/logo.png" } },
    { "id": "swsh5", "name": "Battle Styles", "total": 183, "images": { "logo": "https://images.pokemontcg.io/swsh5/logo.png" } },
    { "id": "swsh45", "name": "Shining Fates", "total": 73, "images": { "logo": "https://images.pokemontcg.io/swsh45/logo.png" } },
    { "id": "swsh4", "name": "Vivid Voltage", "total": 203, "images": { "logo": "https://images.pokemontcg.io/swsh4/logo.png" } },
    { "id": "swsh3", "name": "Darkness Ablaze", "total": 201, "images": { "logo": "https://images.pokemontcg.io/swsh3/logo.png" } },
    { "id": "swsh2", "name": "Rebel Clash", "total": 209, "images": { "logo": "https://images.pokemontcg.io/swsh2/logo.png" } },
    { "id": "swsh1", "name": "Sword & Shield", "total": 216, "images": { "logo": "https://images.pokemontcg.io/swsh1/logo.png" } },
    { "id": "sm12", "name": "Cosmic Eclipse", "total": 271, "images": { "logo": "https://images.pokemontcg.io/sm12/logo.png" } },
    { "id": "sm115", "name": "Hidden Fates", "total": 69, "images": { "logo": "https://images.pokemontcg.io/sm115/logo.png" } },
    { "id": "sm11", "name": "Unified Minds", "total": 258, "images": { "logo": "https://images.pokemontcg.io/sm11/logo.png" } },
    { "id": "sm10", "name": "Unbroken Bonds", "total": 234, "images": { "logo": "https://images.pokemontcg.io/sm10/logo.png" } },
    { "id": "sm9", "name": "Team Up", "total": 196, "images": { "logo": "https://images.pokemontcg.io/sm9/logo.png" } },
    { "id": "sm8", "name": "Lost Thunder", "total": 236, "images": { "logo": "https://images.pokemontcg.io/sm8/logo.png" } },
    { "id": "sm7", "name": "Celestial Storm", "total": 183, "images": { "logo": "https://images.pokemontcg.io/sm7/logo.png" } },
    { "id": "sm6", "name": "Forbidden Light", "total": 146, "images": { "logo": "https://images.pokemontcg.io/sm6/logo.png" } },
    { "id": "sm5", "name": "Ultra Prism", "total": 178, "images": { "logo": "https://images.pokemontcg.io/sm5/logo.png" } },
    { "id": "sm4", "name": "Crimson Invasion", "total": 124, "images": { "logo": "https://images.pokemontcg.io/sm4/logo.png" } },
    { "id": "sm3", "name": "Burning Shadows", "total": 169, "images": { "logo": "https://images.pokemontcg.io/sm3/logo.png" } },
    { "id": "sm2", "name": "Guardians Rising", "total": 169, "images": { "logo": "https://images.pokemontcg.io/sm2/logo.png" } },
    { "id": "sm1", "name": "Sun & Moon", "total": 163, "images": { "logo": "https://images.pokemontcg.io/sm1/logo.png" } },
    { "id": "xy12", "name": "Evolutions", "total": 109, "images": { "logo": "https://images.pokemontcg.io/xy12/logo.png" } },
    { "id": "xy11", "name": "Steam Siege", "total": 116, "images": { "logo": "https://images.pokemontcg.io/xy11/logo.png" } },
    { "id": "xy10", "name": "Fates Collide", "total": 125, "images": { "logo": "https://images.pokemontcg.io/xy10/logo.png" } },
    { "id": "xy9", "name": "BREAKpoint", "total": 123, "images": { "logo": "https://images.pokemontcg.io/xy9/logo.png" } },
    { "id": "xy8", "name": "BREAKthrough", "total": 164, "images": { "logo": "https://images.pokemontcg.io/xy8/logo.png" } },
    { "id": "xy7", "name": "Ancient Origins", "total": 100, "images": { "logo": "https://images.pokemontcg.io/xy7/logo.png" } },
    { "id": "xy6", "name": "Roaring Skies", "total": 110, "images": { "logo": "https://images.pokemontcg.io/xy6/logo.png" } },
    { "id": "xy5", "name": "Primal Clash", "total": 164, "images": { "logo": "https://images.pokemontcg.io/xy5/logo.png" } },
    { "id": "xy4", "name": "Phantom Forces", "total": 122, "images": { "logo": "https://images.pokemontcg.io/xy4/logo.png" } },
    { "id": "xy3", "name": "Furious Fists", "total": 113, "images": { "logo": "https://images.pokemontcg.io/xy3/logo.png" } },
    { "id": "xy2", "name": "Flashfire", "total": 109, "images": { "logo": "https://images.pokemontcg.io/xy2/logo.png" } },
    { "id": "xy1", "name": "XY", "total": 146, "images": { "logo": "https://images.pokemontcg.io/xy1/logo.png" } },
    { "id": "base3", "name": "Fossil", "total": 62, "images": { "logo": "https://images.pokemontcg.io/base3/logo.png" } },
    { "id": "base2", "name": "Jungle", "total": 64, "images": { "logo": "https://images.pokemontcg.io/base2/logo.png" } },
    { "id": "base1", "name": "Base Set", "total": 102, "images": { "logo": "https://images.pokemontcg.io/base1/logo.png" } }
  ]
};
